trigger: none

pool: Default

variables:
- group: BuildVariables
- group: InsiderBuilds

resources:
  repositories:
    - repository: Template
      type: github
      endpoint: gunnargestsson # Service Connection
      name: gunnargestsson/bcbuildtemplate
      ref: master

extends:
  template: /.azureDevOps/CI.yml@Template
  parameters:
    version: "nextminor"
    appVersion: "17.2"
    azureSubscription: ""
    createRuntimePackages: false
    configurationFilePath: '.azureDevOps\build-settings.json'

